name: build

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && ${{ github.ref == 'refs/heads/master' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
